name: Challenges

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT: Project Euler.xcodeproj
  SCHEME: Challenges
  CONFIGURATION: Debug

jobs:
  Tests:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Xcode build library
      run: |
        xcodebuild build -project "${PROJECT}" -scheme "${SCHEME}" \
          -configuration ${CONFIGURATION} \
        | xcpretty && exit ${PIPESTATUS[0]}

    - name: Xcode unit test
      run: |
        xcodebuild test -project "${PROJECT}" -scheme "${SCHEME}" \
          -enableCodeCoverage YES -configuration ${CONFIGURATION} \
        | xcpretty && exit ${PIPESTATUS[0]}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
