name: Challenges

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Challenges:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Xcode unit test
      env:
        NSUnbufferedIO: YES
      run: |
        set -o pipefail && \
        xcodebuild -scheme Challenges build test 2>&1 | xcbeautify && exit ${PIPESTATUS[0]}

    - name: Use ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install slather for code coverage
      run: gem install slather

    - name: Run slather for code coverage
      run: slather

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: xml_report/cobertura.xml
        functionalities: coveragepy,gcov,xcode
